# Pandas Operation

In [2]:
# Add a column to DataFrame Columns
import pandas as pd
aa= pd.read_csv('aa.csv')
aa['Age']= '24'
aa.head()

FileNotFoundError: [Errno 2] File aa.csv does not exist: 'aa.csv'

In [4]:
# Add new columns in a DataFrame using insert()
import pandas as pd
aa= pd.read_csv('aa.csv')
aa.head()

FileNotFoundError: [Errno 2] File aa.csv does not exist: 'aa.csv'

In [5]:
 # Add new columns in a DataFrame using insert()
import pandas as pd
aa= pd.read_csv('aa.csv')
aa.insert(2, column= 'Department', value='B.Sc')

FileNotFoundError: [Errno 2] File aa.csv does not exist: 'aa.csv'

In [6]:
# Convert Pandas DataFrame to Numpy array
# Ex.1
import pandas as pd
pd.DataFrame({'P':[2,3], 'Q':[4,5]}).to_numpy()
info= pd.DataFrame({'P':[2,3], 'Q':[4.0, 5.8]})
info.to_numpy()
info['R']= pd.date_range('2000', periods=2)
info.to_numpy()

array([[2, 4.0, Timestamp('2000-01-01 00:00:00')],
       [3, 5.8, Timestamp('2000-01-02 00:00:00')]], dtype=object)

In [7]:
# Ex.2
import pandas as pd
info= pd.DataFrame([[17, 62, 35], [25, 36, 54], [42, 20, 15], [48, 62, 76]],
                   columns=['x', 'y', 'z'])
print('DataFrame\n--------\n', info)
arr= info.to_numpy()
print('\nNumpy Array\n--------\n', arr)

DataFrame
--------
     x   y   z
0  17  62  35
1  25  36  54
2  42  20  15
3  48  62  76

Numpy Array
--------
 [[17 62 35]
 [25 36 54]
 [42 20 15]
 [48 62 76]]


In [8]:
# Convert Pandas DataFrame to CSV
#Ex.1
import pandas as pd
data= {'Name':['Smith', 'Parker'], 'ID':[101, 102], 'Language':['Python', 'JavaScript']}
info= pd.DataFrame(data)
print('DataFrame Values:\n', info)
csv_data= info.to_csv()
print('\n CSV String Values:\n', csv_data)

DataFrame Values:
      Name   ID    Language
0   Smith  101      Python
1  Parker  102  JavaScript

 CSV String Values:
 ,Name,ID,Language
0,Smith,101,Python
1,Parker,102,JavaScript



In [ ]:
#Ex.2


# Pandas Concatenation

In [2]:
import pandas as pd
a_data= pd.Series(['p','q'])
b_data= pd.Series(['r','s'])
pd.concat([a_data, b_data])

0    p
1    q
0    r
1    s
dtype: object

In [3]:
import pandas as pd
a_data= pd.Series(['p','q'])
b_data= pd.Series(['r','s'])
pd.concat([a_data, b_data], ignore_index= True)

0    p
1    q
2    r
3    s
dtype: object

In [5]:
import pandas as pd
a_data= pd.Series(['p','q'])
b_data= pd.Series(['r','s'])
pd.concat([a_data, b_data], keys=['a_data', 'b_data'])

a_data  0    p
        1    q
b_data  0    r
        1    s
dtype: object

In [6]:
import pandas as pd
a_data= pd.Series(['p','q'])
b_data= pd.Series(['r','s'])
pd.concat([a_data, b_data], keys=['a_data', 'b_data'])
pd.concat([a_data, b_data], keys=['a_data', 'b_data'],
         names=['Series name', 'Row ID'])

Series name  Row ID
a_data       0         p
             1         q
b_data       0         r
             1         s
dtype: object

In [12]:
# Concatenation using append
import pandas as pd
one= pd.DataFrame({
'Name':['Parker', 'Smith', 'Allen', 'John', 'Parker'],
'subject_id':['sub1','sub2','sub4','sub6','sub5'],
'Marks_scored':[98, 90, 87, 69, 87]},
    index=[1,2,3,4,5])
two= pd.DataFrame({
    'Name':['Billy','Brian','Bran', 'Bryce','Betty'],
    'subject_id':['sub2','sub4','sub3','sub6','sub5'],
    'Marks_scored':[89,80,79,97,88]},
    index=[1,2,3,4,5])
print(one.append(two))

     Name subject_id  Marks_scored
1  Parker       sub1            98
2   Smith       sub2            90
3   Allen       sub4            87
4    John       sub6            69
5  Parker       sub5            87
1   Billy       sub2            89
2   Brian       sub4            80
3    Bran       sub3            79
4   Bryce       sub6            97
5   Betty       sub5            88


# Data Operations

### Data Processing

In [3]:
import pandas as pd
info= pd.Series([11,14,17,24,19,32,34,27],
index=[['x','x','x','x','y','y','y','y'],
      ['obj1','obj2','obj3','obj4','obj1','obj2','obj3','obj4']])
info

x  obj1    11
   obj2    14
   obj3    17
   obj4    24
y  obj1    19
   obj2    32
   obj3    34
   obj4    27
dtype: int64

### Partial indexing

In [1]:
import pandas as pd
info=pd.Series([11,14,17,24,19,32,34,27],
              index=[['x','x','x','x','y','y','y','y'],
                    'obj1','obj2','obj3','obj4','obj1','obj2','obj3','obj4'])
info['b']

ValueError: Length of passed values is 8, index implies 9.

### Unstack the data

In [3]:
import pandas as pd
info= pd.Series([11,14,17,24,19,32,34,27],
               index=[['x','x','x','x','y','y','y','y'],
                     ['obj1','obj2','obj3','obj4','obj1','obj2','obj3','obj4']])
# unstack on first level i.e. x,y 
# note that data row-labels are x and y
info.unstack(0)

x   y
obj1  11  19
obj2  14  32
obj3  17  34
obj4  24  27

In [3]:
# unstack based on second level i.e. 'obj'
info.unstack(1)

obj1  obj2  obj3  obj4
x    11    14    17    24
y    19    32    34    27

In [1]:
import pandas as pd
info= pd.Series([11,14,17,24,19,32,34,27],
               index=[['x','x','x','x','y','y','y','y'],
                     ['obj1','obj2','obj3','obj4','obj1','obj2','obj3','obj4']])
# unstack on first level i.e. x, y
# note that data row-lables are x and y
info.unstack(0)


x   y
obj1  11  19
obj2  14  32
obj3  17  34
obj4  24  27

In [2]:
info.stack()

AttributeError: 'Series' object has no attribute 'stack'

### Column indexing

In [8]:
import numpy as np
info= pd.DataFrame(np.arange(12).reshape(4,3),
                  index=[['a','a','b','b'], ['one','two','three','four']],
                  columns=[['num1','num2','nums3'],['x','y','x']])
info

num1 num2 nums3
           x    y     x
a one      0    1     2
  two      3    4     5
b three    6    7     8
  four     9   10    11

In [9]:
# display row index
info.index

MultiIndex([('a',   'one'),
            ('a',   'two'),
            ('b', 'three'),
            ('b',  'four')],
           )

In [4]:
# display columns index
info.columns

AttributeError: 'Series' object has no attribute 'columns'

### Swap and sort level

In [6]:
import numpy as np
info= pd.DataFrame(np.arange(12).reshape(4,3),
                  index=[['a','a','b','b'], ['one','two','three','four']],
                  columns=[['num1','num2','num3'],['x','y','x']])
info.swaplevel('key1','key2')

KeyError: 'Level key1 not found'

In [7]:
info.sort_index(level='key2')

KeyError: 'Level key2 not found'